draft package

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,132 +1,118 @@
 #!/bin/bash
 
 #=================================================
-# GENERIC START
-#=================================================
 # IMPORT GENERIC HELPERS
 #=================================================
 
 source _common.sh
 source /usr/share/yunohost/helpers
 
-### Settings are automatically loaded as bash variables
-### in every app script context, therefore typically these will exist:
-### - $domain
-### - $path
-### - $language
-### - $install_dir
-### - $port
-### ...
+#-------------------------------------------------
+# config_panel.toml settings:
 
-### In the context of upgrade,
-### - resources are automatically provisioned / updated / deleted (depending on existing resources)
-### - a safety backup is automatically created by the core and will be restored if the upgrade fails
+if [ -z "$debug_enabled" ]; then
+	debug_enabled="0"
+	ynh_app_setting_set --app=$app --key=debug_enabled --value="$debug_enabled"
+fi
 
-### This variable describes which upgrade type is occurring, allowing the script to handle different modes:
-### - UPGRADE_PACKAGE if only the YunoHost package has changed
-### - UPGRADE_APP if the upstream app version has changed
-### If your package needs to handle other things, like same-version upgrades or downgrades, please
-### check out the $YNH_APP_UPGRADE_TYPE variable that can contain DOWNGRADE and UPGRADE_SAME too.
-# upgrade_type=$(ynh_check_app_version_changed)
+if [ -z "$log_level" ]; then
+	log_level="WARNING"
+	ynh_app_setting_set --app=$app --key=log_level --value="$log_level"
+fi
+
+if [ -z "$admin_email" ]; then
+	admin_email="${admin}@${domain}"
+    ynh_app_setting_set --app=$app --key=admin_email --value="$admin_email"
+fi
+
+if [ -z "$default_from_email" ]; then
+	default_from_email="${app}@${domain}"
+	ynh_app_setting_set --app=$app --key=default_from_email --value="$default_from_email"
+fi
 
 #=================================================
 # STANDARD UPGRADE STEPS
 #=================================================
-# ENSURE DOWNWARD COMPATIBILITY
-#=================================================
-#ynh_script_progression --message="Ensuring downward compatibility..." --weight=1
-
-### N.B. : the following setting migration snippets are provided as *EXAMPLES*
-### of what you may want to do in some cases (e.g. a setting was not defined on
-### some legacy installs and you therefore want to initiaze stuff during upgrade)
-
-# If db_name doesn't exist, create it
-# if [ -z "$db_name" ]; then
-#     db_name=$(ynh_sanitize_dbid --db_name=$app)
-#     ynh_app_setting_set --app=$app --key=db_name --value=$db_name
-# fi
-
-# If install_dir doesn't exist, create it
-# if [ -z "$install_dir" ]; then
-#     install_dir=/var/www/$app
-#     ynh_app_setting_set --app=$app --key=install_dir --value=$install_dir
-# fi
-
-#=================================================
 # STOP SYSTEMD SERVICE
 #=================================================
-ynh_script_progression --message="Stopping a systemd service..." --weight=1
+ynh_script_progression --message="Stopping systemd service '$app'..." --weight=5
 
-ynh_systemd_action --service_name="$app" --action="stop" --log_path="/var/log/$app/$app.log"
+ynh_systemd_action --service_name=$app --action="stop" --log_path="$log_file"
 
-#=================================================
-# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
-#=================================================
-# DOWNLOAD, CHECK AND UNPACK SOURCE
-#=================================================
-
-ynh_script_progression --message="Upgrading source files..." --weight=1
-
-# Download, check integrity, uncompress and patch the source from manifest.toml
-ynh_setup_source --dest_dir="$install_dir"
-
-### $install_dir will automatically be initialized with some decent
-### permissions by default ... however, you may need to recursively reapply
-### ownership to all files such as after the ynh_setup_source step
-chown -R "$app:www-data" "$install_dir"
 
 #=================================================
-# REAPPLY SYSTEM CONFIGURATIONS
+# SETUP SYSTEMD
 #=================================================
-ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1
+ynh_script_progression --message="Configuring systemd service '$app'..." --weight=5
 
-### This should be a literal copypaste of what happened in the install's "System configuration" section
-
-ynh_add_fpm_config
-
-ynh_add_nginx_config
-
-ynh_add_systemd_config
-
-yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"
-
-ynh_use_logrotate --non-append
-
-ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"
+ynh_add_systemd_config --service=$app --template="systemd.service"
 
 #=================================================
-# RECONFIGURE THE APP (UPDATE CONF, APPLY MIGRATIONS...)
+# PYTHON VIRTUALENV
 #=================================================
-# UPDATE A CONFIG FILE
-#=================================================
-ynh_script_progression --message="Updating a configuration file..." --weight=1
-
-### Same as during install
-###
-### The file will automatically be backed-up if it's found to be manually modified (because
-### ynh_add_config keeps track of the file's checksum)
-
-ynh_add_config --template="some_config_file" --destination="$install_dir/some_config_file"
-
-# FIXME: this should be handled by the core in the future
-### You may need to use chmod 600 instead of 400,
-### for example if the app is expected to be able to modify its own config
-chmod 400 "$install_dir/some_config_file"
-chown "$app:$app" "$install_dir/some_config_file"
-
-### For more complex cases where you want to replace stuff using regexes,
-### you shoud rely on ynh_replace_string (which is basically a wrapper for sed)
-### When doing so, you also need to manually call ynh_store_file_checksum
-###
-### ynh_replace_string --match_string="match_string" --replace_string="replace_string" --target_file="$install_dir/some_config_file"
-### ynh_store_file_checksum --file="$install_dir/some_config_file"
+ynh_script_progression --message="Create and setup Python virtualenv..." --weight=45
+cp ../conf/requirements.txt "$data_dir/requirements.txt"
+myynh_setup_python_venv
 
 #=================================================
-# START SYSTEMD SERVICE
-#=================================================
-ynh_script_progression --message="Starting a systemd service..." --weight=1
+# copy config files
+# ================================================
+ynh_script_progression --message="Create project configuration files..."
 
-ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"
+ynh_add_config --template="gunicorn.conf.py" --destination="$data_dir/gunicorn.conf.py"
+
+ynh_add_config --template="manage.py" --destination="$data_dir/manage.py"
+chmod -c +x "$data_dir/manage.py"
+
+ynh_add_config --template="settings.py" --destination="$data_dir/settings.py"
+ynh_add_config --template="setup_user.py" --destination="$data_dir/setup_user.py"
+ynh_add_config --template="urls.py" --destination="$data_dir/urls.py"
+ynh_add_config --template="wsgi.py" --destination="$data_dir/wsgi.py"
+
+#=================================================
+# MIGRATE PYINVENTORY
+#=================================================
+ynh_script_progression --message="migrate/collectstatic/createadmin..." --weight=10
+
+cd "$data_dir" || exit
+
+# Just for debugging:
+./manage.py diffsettings
+
+./manage.py migrate --no-input
+./manage.py collectstatic --no-input
+
+# Create/update Django superuser (set unusable password, because auth done via SSOwat):
+./manage.py create_superuser --username="$admin" --email="$(ynh_user_get_info "$admin" mail)"
+
+# Check the configuration
+# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
+./manage.py check --deploy || true
+
+
+#=================================================
+# SETUP LOGROTATE
+#=================================================
+ynh_script_progression --message="Upgrading logrotate configuration..."
+
+# Use logrotate to manage app-specific logfile(s)
+ynh_use_logrotate --logfile="$log_file" --specific_user=$app --non-append
+
+#=================================================
+# GENERIC FINALIZATION
+#=================================================
+# SECURE FILES AND DIRECTORIES
+#=================================================
+ynh_script_progression --message="Set file permissions..."
+myynh_fix_file_permissions
+
+#=================================================
+# Start the app server via systemd
+#=================================================
+ynh_script_progression --message="Starting systemd service '$app'..." --weight=5
+
+yunohost service add $app
+ynh_systemd_action --service_name=$app --action="start" --log_path="$log_file"
 
 #=================================================
 # END OF SCRIPT
